
server:
  port: 8200

spring:
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: root2
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true