server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root2
    password: password
  jpa:
    hibernate:
      ddl-auto: update