server:
  port: 8300

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root2
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/